// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxZIdTa1meiUGOsuffkRL2MVj1WIPi_Ks',
    appId: '1:439917788902:web:b02f161801f0604fb38527',
    messagingSenderId: '439917788902',
    projectId: 'login-form-9245d',
    authDomain: 'login-form-9245d.firebaseapp.com',
    storageBucket: 'login-form-9245d.appspot.com',
    measurementId: 'G-B71972J74L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8A50YX3E45QhO1HBAx65XzCApniUzOQI',
    appId: '1:439917788902:android:7354c55aac07bff4b38527',
    messagingSenderId: '439917788902',
    projectId: 'login-form-9245d',
    storageBucket: 'login-form-9245d.appspot.com',
  );
}
